### ISSUE TITLE
能否移植到嵌入式设备？实现rgb转hevc?

### ISSUE THREAD

**Issue by zx310** [WangXuan95/NBLI#1]
王博你好，我最近正在研究嵌入式设备h265编码，恰好看到你的开源项目，才有了这个想法。多谢

**Comment by WangXuan95** [comment]
你好，

我没有去做彩色图像编码，需要你自己去做。

首先，RGB 的彩色图像在 HEVC 中实际上是转化为 YUV 色域（最常用的是 YUV 4:2:0），然后再进行压缩的，这一步并不复杂，你可以查一下。

然后，本库的代码实际上使用的是 HEVC 的 YUV 4:2:0 格式，但让 U/V 通道全部为像素中值 (0x80)，这样得到的都是灰度图像。但是要编码 U/V 通道，还需要加一些代码，包括 U/V 通道的预测、coefficent 的编码，这一步还是有一定的工作量的，你可以先把本库的代码读懂，然后去阅读 [HEVC 官方的 HM 代码](https://vcgit.hhi.fraunhofer.de/jvet/HM) ，然后在本库的基础上加。

最后，本库进行的是详尽的CU划分策略和预测的搜索，因此效率最低（虽然压缩率会高一些），在实际应用（尤其是嵌入式）中，应该对搜索策略进行剪枝。最基础的剪枝策略是计算预测块和原始像素块之间的SAD（绝对值差之和）或SATD（哈达玛变换后的绝对值差之和），然后找出几个让SAD或SATD最小化的预测模式，只对它们进行详尽的RD-cost的搜索。详见参考资料。

参考资料：
[HEVC 官方的 HM 代码](https://vcgit.hhi.fraunhofer.de/jvet/HM)
[H.265/HEVC 帧内编码详解：CU层次结构、预测、变换、量化、编码](https://zhuanlan.zhihu.com/p/607679114)
《新一代高效视频编码H.265 HEVC  原理、标准与实现》 万帅，杨付正编著

**Comment by zx310** [comment]
> 
感谢王博指导，受益匪浅。
