### ISSUE TITLE
是否应当将可执行文件放在Releases中

### ISSUE THREAD

**Issue by inschrift-spruch-raum** [WangXuan95/NBLI#2]
我注意到您在新版本中更改了可执行文件的存储位置,不过这似乎仍然存在问题,将他们放在Releases中似乎是更好的选择
顺便一提,自述文件中的指向链接已失效

**Comment by WangXuan95** [comment]
可执行文件能用就行。
README中哪个链接失效了？

**Comment by inschrift-spruch-raum** [comment]
![image](https://github.com/user-attachments/assets/67ebf932-0541-46c5-b437-0289a62d58a5)
